package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.databinding.Bindable
import android.support.constraint.ConstraintLayout
import android.support.v7.app.AppCompatActivity
import android.view.View
import android.widget.*
import ca.csf.mobile2.tp2.R
import ca.csf.mobile2.tp2.databinding.ActivityQuestionBinding
import org.androidannotations.annotations.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@DataBound
@EActivity(R.layout.activity_question)
class QuestionActivity : AppCompatActivity() {

    @Bean
    protected lateinit var questionService: QuestionService

    @InstanceState
    protected lateinit var viewModel: QuestionActivityViewModel

    protected fun onCreate(@BindingObject dataBinder: ActivityQuestionBinding) {
        if(!this::viewModel.isInitialized)
            viewModel = QuestionActivityViewModel(null)

        dataBinder.viewModel = viewModel
    }

    @AfterViews
    @Click(R.id.answers_view)
    protected fun fetchRandomQuestion() {
        questionService.getRandomQuestion(
            this::onQuestionFound,
            this::onConnectivityError,
            this::onServerError
        )
        viewModel.hasClickedChoice = false
    }

    @Click(R.id.choice1_button)
    protected fun onChoice1ButtonClick() {
        viewModel.hasClickedChoice = true
    }

    @Click(R.id.choice2_button)
    protected fun onChoice2ButtonClick() {
        viewModel.hasClickedChoice = true
    }

    @Click(R.id.retry_button)
    protected fun onRetryButtonClick() {

    }

    @UiThread
    protected fun onQuestionFound(question: Question) {
        viewModel.question = question
    }

    @UiThread
    protected fun onConnectivityError() {
    }

    @UiThread
    protected fun onServerError() {
    }

}
